apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: ultra-sync
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
