apiVersion: v2
name: ultra-sync
description: Ultra-Sync Super App — Logistics, Wallet & Chat microservices
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - logistics
  - wallet
  - super-app
maintainers:
  - name: CHANON
    email: chanonforworkshop@gmail.com
