apiVersion: v1
kind: Service
metadata:
  name: wallet-svc
  namespace: ultra-sync
  labels:
    app: wallet
spec:
  selector:
    app: wallet
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
